[package]
name = "crud-api"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
diesel = { version = "2.1.6", features = ["sqlite", "r2d2"] }
dotenv = "0.15"
env_logger = "0.11"
log = "0.4.21"